// <auto-generated />
using System;
using Cascade.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cascade.Database.Migrations
{
    [DbContext(typeof(CascadeDbContext))]
    [Migration("20251204091145_AddAutomationSessions")]
    partial class AddAutomationSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Cascade.Database.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActiveVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("1.0.0")
                        .HasColumnName("active_version");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("InstructionList")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instruction_list");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_executed_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TargetApplication")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_application");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TargetApplication");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.AgentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CapabilitiesSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_snapshot");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("InstructionListSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instruction_list_snapshot");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("ScriptIdsSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("script_ids_snapshot");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("AgentId", "Version")
                        .IsUnique();

                    b.ToTable("agent_versions", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.AutomationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ExecutionRecordId")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_record_id");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("released_at");

                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ExecutionRecordId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("automation_sessions", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.Configuration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsEncrypted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_encrypted");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("String")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("configurations", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("Logs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("logs");

                    b.Property<string>("ResultData")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_data");

                    b.Property<string>("SessionId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("success");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_description");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("UserId");

                    b.ToTable("execution_records", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExecutionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<int>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_id");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT")
                        .HasColumnName("parameters");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<byte[]>("Screenshot")
                        .HasColumnType("BLOB")
                        .HasColumnName("screenshot");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("execution_steps", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExplorationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActionTestResult")
                        .HasColumnType("TEXT")
                        .HasColumnName("action_test_result");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at");

                    b.Property<string>("ElementData")
                        .HasColumnType("TEXT")
                        .HasColumnName("element_data");

                    b.Property<string>("NavigationPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("navigation_path");

                    b.Property<string>("OcrText")
                        .HasColumnType("TEXT")
                        .HasColumnName("ocr_text");

                    b.Property<byte[]>("Screenshot")
                        .HasColumnType("BLOB")
                        .HasColumnName("screenshot");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("WindowTitle")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("window_title");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Type");

                    b.ToTable("exploration_results", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExplorationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedGoals")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_goals");

                    b.Property<string>("FailedGoals")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("failed_goals");

                    b.Property<Guid?>("GeneratedAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_agent_id");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("goals");

                    b.Property<string>("InstructionManual")
                        .HasColumnType("TEXT")
                        .HasColumnName("instruction_manual");

                    b.Property<float>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0f)
                        .HasColumnName("progress");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TargetApplication")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_application");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAgentId");

                    b.HasIndex("Status");

                    b.HasIndex("TargetApplication");

                    b.ToTable("exploration_sessions", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CompilationErrors")
                        .HasColumnType("TEXT")
                        .HasColumnName("compilation_errors");

                    b.Property<byte[]>("CompiledAssembly")
                        .HasColumnType("BLOB")
                        .HasColumnName("compiled_assembly");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("1.0.0")
                        .HasColumnName("current_version");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastCompiledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_compiled_at");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("MethodName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("method_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_code");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("TypeName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("type_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("scripts", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.ScriptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("change_description");

                    b.Property<byte[]>("CompiledAssembly")
                        .HasColumnType("BLOB")
                        .HasColumnName("compiled_assembly");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("TEXT")
                        .HasColumnName("script_id");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_code");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId");

                    b.HasIndex("ScriptId", "Version")
                        .IsUnique();

                    b.ToTable("script_versions", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.SessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AutomationSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("automation_session_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("AutomationSessionId")
                        .HasDatabaseName("idx_session_events_session");

                    b.ToTable("session_events", (string)null);
                });

            modelBuilder.Entity("Cascade.Database.Entities.AgentVersion", b =>
                {
                    b.HasOne("Cascade.Database.Entities.Agent", "Agent")
                        .WithMany("Versions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Cascade.Database.Entities.AutomationSession", b =>
                {
                    b.HasOne("Cascade.Database.Entities.Agent", "Agent")
                        .WithMany("Sessions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cascade.Database.Entities.ExecutionRecord", "ExecutionRecord")
                        .WithMany("Sessions")
                        .HasForeignKey("ExecutionRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("ExecutionRecord");
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExecutionRecord", b =>
                {
                    b.HasOne("Cascade.Database.Entities.Agent", "Agent")
                        .WithMany("Executions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExecutionStep", b =>
                {
                    b.HasOne("Cascade.Database.Entities.ExecutionRecord", "Execution")
                        .WithMany("Steps")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExplorationResult", b =>
                {
                    b.HasOne("Cascade.Database.Entities.ExplorationSession", "Session")
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExplorationSession", b =>
                {
                    b.HasOne("Cascade.Database.Entities.Agent", "GeneratedAgent")
                        .WithMany()
                        .HasForeignKey("GeneratedAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GeneratedAgent");
                });

            modelBuilder.Entity("Cascade.Database.Entities.Script", b =>
                {
                    b.HasOne("Cascade.Database.Entities.Agent", "Agent")
                        .WithMany("Scripts")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Cascade.Database.Entities.ScriptVersion", b =>
                {
                    b.HasOne("Cascade.Database.Entities.Script", "Script")
                        .WithMany("Versions")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Script");
                });

            modelBuilder.Entity("Cascade.Database.Entities.SessionEvent", b =>
                {
                    b.HasOne("Cascade.Database.Entities.AutomationSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("AutomationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Cascade.Database.Entities.Agent", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Scripts");

                    b.Navigation("Sessions");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Cascade.Database.Entities.AutomationSession", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExecutionRecord", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Cascade.Database.Entities.ExplorationSession", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Cascade.Database.Entities.Script", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
